---
- hosts: webservers
  become: true
  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: true

    - name: Copy index.html to Apache web root
      copy:
        src: index.html
        dest: /var/www/html/index.html
